Repository slkarsh/swapi-trivia, pull requests merged in 2019-10, with the labels that each got.

#2 Add styling to Form component
  src/components/App/App.js
  src/components/LoginForm/LoginForm.js
  src/components/LoginForm/LoginForm.scss
  src/index.scss
Labels: styling

#8 UI enhancements and pass props down to components
  public/index.html
  src/components/App/App.js
  src/components/CharacterCard/CharacterCard.js
  src/components/CharactersContainer/CharactersContainer.js
  src/components/Favorites/Favorites.js
  src/components/Favorites/Favorites.scss
  src/components/Favorites/Favorites.test.js
  src/components/LoginForm/LoginForm.js
  src/components/LoginForm/LoginForm.scss
  src/components/MovieCard/MovieCard.scss
  src/components/NavBar/NavBar.scss
  src/components/Quote/Quote.js
  src/components/Quote/Quote.scss
  src/components/QuoteContainer/QuoteContainer.js
Labels: enhancement, styling

#9 Slk render characters
  src/apis/apiCalls.js
  src/components/App/App.js
  src/components/App/App.scss
  src/components/CharacterCard/CharacterCard.js
  src/components/CharactersContainer/CharactersContainer.js
  src/components/MovieCard/MovieCard.js
  src/components/MoviesContainer/MoviesContainer.js
  src/components/MoviesContainer/MoviesContainer.scss
  src/components/SelectedMovie/SelectedMovie.js
  src/index.scss
Labels: bug, help wanted

#10 Jest, snapshot testing, and PropTypes prop validation
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/App/__snapshots__/App.test.js.snap
  src/components/CharacterCard/CharacterCard.js
  src/components/CharacterCard/CharacterCard.test.js
  src/components/CharacterCard/__snapshots__/CharacterCard.test.js.snap
  src/components/CharactersContainer/CharactersContainer.js
  src/components/CharactersContainer/CharactersContainer.test.js
  src/components/CharactersContainer/__snapshots__/CharactersContainer.test.js.snap
  src/components/Favorites/Favorites.js
  src/components/Favorites/Favorites.test.js
  src/components/Favorites/__snapshots__/Favorites.test.js.snap
  src/components/LoginForm/LoginForm.js
  src/components/LoginForm/LoginForm.test.js
  src/components/LoginForm/__snapshots__/LoginForm.test.js.snap
  src/components/MovieCard/MovieCard.js
  src/components/MovieCard/MovieCard.test.js
  src/components/MovieCard/__snapshots__/MovieCard.test.js.snap
  src/components/MoviesContainer/MoviesContainer.js
  src/components/MoviesContainer/MoviesContainer.test.js
  src/components/MoviesContainer/__snapshots__/MoviesContainer.test.js.snap
  src/components/NavBar/NavBar.js
  src/components/NavBar/NavBar.test.js
  src/components/NavBar/__snapshots__/NavBar.test.js.snap
  src/components/Quote/Quote.js
  src/components/Quote/Quote.test.js
  src/components/Quote/__snapshots__/Quote.test.js.snap
  src/components/QuoteContainer/QuoteContainer.js
  src/components/QuoteContainer/QuoteContainer.test.js
  src/components/QuoteContainer/__snapshots__/QuoteContainer.test.js.snap
  src/components/SelectedMovie/SelectedMovie.js
  src/components/SelectedMovie/SelectedMovie.test.js
  src/components/SelectedMovie/__snapshots__/SelectedMovie.test.js.snap
  src/index.js
  src/index.scss
  src/setupTests.js
Labels: documentation, enhancement

#11 Edb loading screen
  .vscode/settings.json
  src/apis/apiCalls.js
  src/components/CharacterCard/CharacterCard.js
  src/components/CharactersContainer/CharactersContainer.js
  src/components/LoginForm/LoginForm.js
  src/components/MovieCard/MovieCard.js
  src/components/MoviesContainer/MoviesContainer.js
  src/components/NavBar/NavBar.js
  src/components/Quote/Quote.js
  src/components/Quote/Quote.scss
  src/components/QuoteContainer/QuoteContainer.js
  src/components/SelectedMovie/SelectedMovie.js
  src/components/SelectedMovie/SelectedMovie.scss
Labels: documentation, enhancement

#13 Edb loading screen
  src/components/CharacterCard/CharacterCard.js
  src/components/MovieCard/MovieCard.js
  src/components/MovieCard/MovieCard.scss
  src/components/MoviesContainer/MoviesContainer.scss
  src/components/NavBar/NavBar.scss
  src/images/1.jpg
  src/images/2.jpg
  src/images/3.jpg
  src/images/4.jpg
  src/images/5.jpg
  src/images/6.jpg
  src/images/7.jpg
Labels: documentation, enhancement

#15 Add testing to login component
  src/components/CharacterCard/CharacterCard.test.js
  src/components/CharacterCard/__snapshots__/CharacterCard.test.js.snap
  src/components/LoginForm/LoginForm.test.js
  src/components/MovieCard/__snapshots__/MovieCard.test.js.snap
  src/components/Quote/__snapshots__/Quote.test.js.snap
  src/components/SelectedMovie/__snapshots__/SelectedMovie.test.js.snap
Labels: testing

#16 Slk favorites
  src/apis/apiCalls.js
  src/components/App/App.js
  src/components/CharacterCard/CharacterCard.js
  src/components/CharacterCard/CharacterCard.scss
  src/components/CharactersContainer/CharactersContainer.js
  src/components/Favorites/Favorites.js
  src/components/NavBar/NavBar.js
  src/components/SelectedMovie/SelectedMovie.js
Labels: enhancement

#18 A punch of enhancements
  src/components/App/__snapshots__/App.test.js.snap
  src/components/CharacterCard/__snapshots__/CharacterCard.test.js.snap
  src/components/LoginForm/LoginForm.scss
  src/components/MovieCard/MovieCard.js
  src/components/MovieCard/MovieCard.scss
  src/components/MoviesContainer/MoviesContainer.scss
  src/components/NavBar/NavBar.js
  src/components/NavBar/NavBar.scss
  src/components/Quote/Quote.scss
Labels: enhancement, testing

#19 Styling and make favorite button toggle, and work in Favorite section
  src/components/App/App.js
  src/components/CharacterCard/CharacterCard.js
  src/components/CharacterCard/CharacterCard.scss
  src/components/CharactersContainer/CharactersContainer.js
  src/components/Favorites/Favorites.js
  src/components/LoginForm/LoginForm.scss
  src/components/MovieCard/MovieCard.scss
  src/components/MoviesContainer/MoviesContainer.scss
  src/components/Quote/Quote.scss
  src/components/SelectedMovie/SelectedMovie.js
Labels: documentation, enhancement, styling

#21 Edb misc
  public/index.html
  public/manifest.json
  src/apis/apiCalls.js
  src/components/App/App.js
  src/components/CharacterCard/CharacterCard.js
  src/components/CharacterCard/CharacterCard.scss
  src/components/CharactersContainer/CharactersContainer.js
  src/components/Favorites/Favorites.js
  src/components/Favorites/Favorites.scss
  src/components/LoginForm/LoginForm.js
  src/components/LoginForm/LoginForm.scss
  src/components/MovieCard/MovieCard.js
  src/components/MovieCard/MovieCard.scss
  src/components/NavBar/NavBar.js
  src/components/NavBar/NavBar.scss
  src/components/Quote/Quote.js
  src/components/Quote/Quote.scss
  src/components/SelectedMovie/SelectedMovie.js
  src/images/background-image.jpg
  src/images/favicon.ico
  src/index.scss
Labels: documentation, enhancement, styling

#24 Pass failing tests left
  src/components/App/App.js
  src/components/CharacterCard/CharacterCard.js
  src/components/CharacterCard/CharacterCard.test.js
  src/components/LoginForm/LoginForm.test.js
Labels: documentation
